#!/usr/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# This is the multiple monitor config for my latop

if [[ $(xrandr -q | grep 'HDMI-2 connected') ]]; then
	xrandr --output eDP1 --mode 1920x1080 --rotate normal --output HDMI2 --primary --mode 1920x1080 --rotate normal --right-of eDP1
	bspc monitor HDMI-2 -d I II III IV V
	bspc monitor eDP-1 -d VI VII VIII IX X
else
	bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Desktops apps rules

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='II' follow=on
bspc rule -a firefox desktop='II' follow=on
bspc rule -a Thunar desktop='III' follow=on
bspc rule -a subl desktop='IV' follow=on
bspc rule -a okular desktop='V'
bspc rule -a code desktop='V' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Wallpaper
feh --bg-fill $HOME/Images/Wallpapers/tanjiro.png
# Launch polybar
sh $HOME/.config/polybar/launch.sh
# Transparencies
exec picom
# Windows name for java applications
wmname LG3D
